In [1]:
import pandas as pd
import numpy as np

In [17]:
descriptor_table = pd.read_csv("Descriptors.csv")
descriptor_table[["sth", "B", "Patient ID", "Date"]] = descriptor_table["MRID"].str.split("_", expand=True)
descriptor_table.sort_values(by=["Patient ID", "Age"])
descriptor_table["Age-rounded"] = descriptor_table["Age"].round()
descriptor_table["Age-rounded"].max() - descriptor_table["Age-rounded"].min()s

55.0

In [3]:
median_age = descriptor_table["Age-rounded"].median()

In [4]:
descriptor_table['Age_Group'] = descriptor_table['Age'] < median_age

# Map True to 'young' and False to 'old'
descriptor_table['Age_Group'] = descriptor_table['Age_Group'].map({True: 'young', False: 'old'})

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
grouped = descriptor_table.groupby('Patient ID')
print(grouped)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7acd2ae798d0>

In [7]:
# Extract unique Patient IDs
unique_patient_ids = descriptor_table['Patient ID'].unique()

# Shuffle the list of unique Patient IDs
np.random.shuffle(unique_patient_ids)

# Calculate the number of IDs for training and testing
total_ids = len(unique_patient_ids)
train_size = int(total_ids * 0.8)

# Assign 80% of IDs to train and 20% to test
train_ids = unique_patient_ids[:train_size]
test_ids = unique_patient_ids[train_size:]

# Create DataFrames for train and test
train_df = pd.DataFrame({'Patient ID': train_ids, 'dataset': 'train'})
test_df = pd.DataFrame({'Patient ID': test_ids, 'dataset': 'test'})

# Concatenate train and test DataFrames
full_df = pd.concat([train_df, test_df])

# Merge with the original DataFrame to assign 'dataset' to each row
result_df = pd.merge(descriptor_table, full_df, on='Patient ID', how='left')

# Display or save the resulting DataFrame
print(result_df)

                       MRID        Age Diagnosis Sex  sth  B Patient ID  \
0     002_S_0413_2017-06-21  87.421150        CN   F  002  S       0413
1     002_S_1155_2017-04-24  68.102533       MCI   M  002  S       1155
2     002_S_1155_2018-05-08  69.140178       MCI   M  002  S       1155
3     002_S_1261_2017-03-15  81.145175       MCI   F  002  S       1261
4     002_S_4473_2017-03-07  79.854073       MCI   M  002  S       4473
...                     ...        ...       ...  ..  ... ..        ...
2248  941_S_5193_2015-04-02  74.306982        CN   F  941  S       5193
2249  941_S_5193_2017-06-09  76.494524        CN   F  941  S       5193
2250  941_S_6058_2019-08-14  70.312320        CN   F  941  S       6058
2251  941_S_6068_2019-09-10  77.853388       MCI   M  941  S       6068
2252  941_S_6575_2019-09-16  74.529432        CN   M  941  S       6575

            Date  Age-rounded Age_Group dataset
0     2017-06-21         87.0       old   train
1     2017-04-24         68.0     young   train
2     2018-05-08         69.0     young   train
3     2017-03-15         81.0       old   train
4     2017-03-07         80.0       old   train
...          ...          ...       ...     ...
2248  2015-04-02         74.0       old   train
2249  2017-06-09         76.0       old   train
2250  2019-08-14         70.0     young   train
2251  2019-09-10         78.0       old   train
2252  2019-09-16         75.0       old   train

[2253 rows x 11 columns]

In [8]:
result_df

,MRID,Age,Diagnosis,Sex,sth,B,Patient ID,Date,Age-rounded,Age_Group,dataset
0,002_S_0413_2017-06-21,87.421150,CN,F,002,S,0413,2017-06-21,87.0,old,train
1,002_S_1155_2017-04-24,68.102533,MCI,M,002,S,1155,2017-04-24,68.0,young,train
2,002_S_1155_2018-05-08,69.140178,MCI,M,002,S,1155,2018-05-08,69.0,young,train
3,002_S_1261_2017-03-15,81.145175,MCI,F,002,S,1261,2017-03-15,81.0,old,train
4,002_S_4473_2017-03-07,79.854073,MCI,M,002,S,4473,2017-03-07,80.0,old,train
...,...,...,...,...,...,...,...,...,...,...,...
2248,941_S_5193_2015-04-02,74.306982,CN,F,941,S,5193,2015-04-02,74.0,old,train
2249,941_S_5193_2017-06-09,76.494524,CN,F,941,S,5193,2017-06-09,76.0,old,train
2250,941_S_6058_2019-08-14,70.312320,CN,F,941,S,6058,2019-08-14,70.0,young,train
2251,941_S_6068_2019-09-10,77.853388,MCI,M,941,S,6068,2019-09-10,78.0,old,train
2252,941_S_6575_2019-09-16,74.529432,CN,M,941,S,6575,2019-09-16,75.0,old,train

In [9]:
# separate into train and test df
# Filter rows for train and test datasets
train_df = result_df[result_df['dataset'] == 'train']
test_df = result_df[result_df['dataset'] == 'test']
train_df

,MRID,Age,Diagnosis,Sex,sth,B,Patient ID,Date,Age-rounded,Age_Group,dataset
0,002_S_0413_2017-06-21,87.421150,CN,F,002,S,0413,2017-06-21,87.0,old,train
1,002_S_1155_2017-04-24,68.102533,MCI,M,002,S,1155,2017-04-24,68.0,young,train
2,002_S_1155_2018-05-08,69.140178,MCI,M,002,S,1155,2018-05-08,69.0,young,train
3,002_S_1261_2017-03-15,81.145175,MCI,F,002,S,1261,2017-03-15,81.0,old,train
4,002_S_4473_2017-03-07,79.854073,MCI,M,002,S,4473,2017-03-07,80.0,old,train
...,...,...,...,...,...,...,...,...,...,...,...
2248,941_S_5193_2015-04-02,74.306982,CN,F,941,S,5193,2015-04-02,74.0,old,train
2249,941_S_5193_2017-06-09,76.494524,CN,F,941,S,5193,2017-06-09,76.0,old,train
2250,941_S_6058_2019-08-14,70.312320,CN,F,941,S,6058,2019-08-14,70.0,young,train
2251,941_S_6068_2019-09-10,77.853388,MCI,M,941,S,6068,2019-09-10,78.0,old,train
2252,941_S_6575_2019-09-16,74.529432,CN,M,941,S,6575,2019-09-16,75.0,old,train

In [10]:
# discard longitudinal data in the train_df by only keeping the first scan
train_df = train_df.groupby('Patient ID').apply(lambda x: x.loc[x['Age'].idxmin()]).reset_index(drop=True)

In [11]:
# split train_df into young_train_df and old_train_df
young_train_df = train_df[train_df["Age_Group"] == "young"].reset_index(drop=True)
old_train_df = train_df[train_df["Age_Group"] == "old"].reset_index(drop=True)

# Filter rows for young and old age groups in the test set
young_test_df = test_df[test_df["Age_Group"] == "young"].reset_index(drop=True)
old_test_df = test_df[test_df["Age_Group"] == "old"].reset_index(drop=True)

In [14]:
# Exporting DataFrames to CSV files
young_train_df.to_csv("young_train_df.csv", index=False)
young_test_df.to_csv("young_test_df.csv", index=False)
old_train_df.to_csv("old_train_df.csv", index=False)
old_test_df.to_csv("old_test_df.csv", index=False)

In [ ]:
import numpy as np
import os
import nibabel as nib
yng_imgs_tr = []
yng_age_tr = []
yng_AD_tr = []

yng_imgs_te = []
yng_age_te = []
yng_AD_te = []

old_imgs_tr = []
old_age_tr = []
old_AD_tr = []

old_imgs_te = []
old_age_te = []
old_AD_te = []


# yng_imgs_tr 
# get the list of 
yng_imgs_tr_list = young_train_df["MRID"]
# for i in range(10):
for i in range(len(yng_imgs_tr_list)):
    # get filename
    cur_img_file = nib.load(os.path.join('adni_data', yng_imgs_tr_list[i], yng_imgs_tr_list[i]+"_MNI152_registered.nii.gz"))
    cur_img_np = cur_img_file.get_fdata()
    cur_img_np_sliced = cur_img_np[:,int(cur_img_np.shape[1]/2-30):int(cur_img_np.shape[1]/2+30),:]
    slice_thickness = cur_img_np_sliced.shape[1]
    for j in range(slice_thickness):
        cur_slice = cur_img_np_sliced[:,j,:]
        # normalize the slice
        cur_slice = (cur_slice / np.max(cur_slice))  * 2 - 1
        yng_imgs_tr.append(cur_slice)
        cur_age = young_train_df[young_train_df["MRID"] == yng_imgs_tr_list[i]]["Age-rounded"].values
        yng_age_tr.append(cur_age[0])
        cur_condition = young_train_df[young_train_df["MRID"] == yng_imgs_tr_list[i]]["Diagnosis"].values
        yng_AD_tr.append(cur_condition[0])
        
yng_imgs_te_list = young_test_df["MRID"]
# for i in range(10):
for i in range(len(yng_imgs_te_list)):
    # get filename
    cur_img_file = nib.load(os.path.join('adni_data', yng_imgs_te_list[i], yng_imgs_te_list[i]+"_MNI152_registered.nii.gz"))
    cur_img_np = cur_img_file.get_fdata()
    cur_img_np_sliced = cur_img_np[:,int(cur_img_np.shape[1]/2-30):int(cur_img_np.shape[1]/2+30),:]
    slice_thickness = cur_img_np_sliced.shape[1]
    for j in range(slice_thickness):
        cur_slice = cur_img_np_sliced[:,j,:]
        # normalize the slice
        cur_slice = (cur_slice / np.max(cur_slice))  * 2 - 1
        yng_imgs_te.append(cur_slice)
        cur_age = young_test_df[young_test_df["MRID"] == yng_imgs_te_list[i]]["Age-rounded"].values
        yng_age_te.append(cur_age)
        cur_condition = young_test_df[young_test_df["MRID"] == yng_imgs_te_list[i]]["Diagnosis"].values
        yng_AD_te.append(cur_condition[0])
        
old_imgs_tr_list = old_train_df["MRID"]
# for i in range(10):
for i in range(len(old_imgs_tr_list)):
    # get filename
    cur_img_file = nib.load(os.path.join('adni_data', old_imgs_tr_list[i], old_imgs_tr_list[i]+"_MNI152_registered.nii.gz"))
    cur_img_np = cur_img_file.get_fdata()
    cur_img_np_sliced = cur_img_np[:,int(cur_img_np.shape[1]/2-30):int(cur_img_np.shape[1]/2+30),:]
    slice_thickness = cur_img_np_sliced.shape[1]
    for j in range(slice_thickness):
        cur_slice = cur_img_np_sliced[:,j,:]
        # normalize the slice
        cur_slice = (cur_slice / np.max(cur_slice)) * 2 - 1
        old_imgs_tr.append(cur_slice)
        cur_age = old_train_df[old_train_df["MRID"] == old_imgs_tr_list[i]]["Age-rounded"].values
        old_age_tr.append(cur_age[0])
        cur_condition = old_train_df[old_train_df["MRID"] == old_imgs_tr_list[i]]["Diagnosis"].values
        old_AD_tr.append(cur_condition[0])
        
old_imgs_te_list = old_test_df["MRID"]
# for i in range(10):
for i in range(len(old_imgs_te_list)):
    # get filename
    cur_img_file = nib.load(os.path.join('adni_data', old_imgs_te_list[i], old_imgs_te_list[i]+"_MNI152_registered.nii.gz"))
    cur_img_np = cur_img_file.get_fdata()
    cur_img_np_sliced = cur_img_np[:,int(cur_img_np.shape[1]/2-30):int(cur_img_np.shape[1]/2+30),:]
    slice_thickness = cur_img_np_sliced.shape[1]
    for j in range(slice_thickness):
        cur_slice = cur_img_np_sliced[:,j,:]
        # normalize the slice
        cur_slice = (cur_slice / np.max(cur_slice)) * 2 - 1
        old_imgs_te.append(cur_slice)
        cur_age = old_test_df[old_test_df["MRID"] == old_imgs_te_list[i]]["Age-rounded"].values
        old_age_te.append(cur_age)
        cur_condition = old_test_df[old_test_df["MRID"] == old_imgs_te_list[i]]["Diagnosis"].values
        old_AD_te.append(cur_condition[0])

yng_imgs_tr_array = np.stack(yng_imgs_tr, axis = 0)
yng_imgs_te_array = np.stack(yng_imgs_te, axis = 0)
old_imgs_tr_array = np.stack(old_imgs_tr, axis = 0)
old_imgs_te_array = np.stack(old_imgs_te, axis = 0)

In [ ]:
# transcode AD condition from text to ord vector
# Mapping from category to numpy array representation
category_mapping = {"CN": [0, 0], "MCI": [0, 1], "AD": [1, 1]}

# Generate the corresponding numpy array
yng_AD_tr_array = np.array([category_mapping[category] for category in yng_AD_tr])
yng_AD_te_array = np.array([category_mapping[category] for category in yng_AD_te])
old_AD_tr_array = np.array([category_mapping[category] for category in old_AD_tr])
old_AD_te_array = np.array([category_mapping[category] for category in old_AD_te])

In [ ]:

print("Length of yng_age_tr:", len(yng_age_tr))
print("Length of yng_AD_tr:", len(yng_AD_tr))

print("Length of yng_age_te:", len(yng_age_te))
print("Length of yng_AD_te:", len(yng_AD_te))

print("Length of old_age_tr:", len(old_age_tr))
print("Length of old_AD_tr:", len(old_AD_tr))

print("Length of old_age_te:", len(old_age_te))
print("Length of old_AD_te:", len(old_AD_te))


print(yng_imgs_tr_array.shape)
print(yng_imgs_te_array.shape)
print(old_imgs_tr_array.shape)
print(old_imgs_te_array.shape)

In [ ]:
from scipy import interpolate

def resample_stack_pytorch(original_stack, new_width, new_height, device='cuda'):
    # Move the original stack to the specified device (GPU or CPU)
    original_stack_tensor = torch.from_numpy(original_stack).to(device)
    
    # Add an extra dimension for the channel to satisfy the shape requirement (N, C, H, W)
    original_stack_tensor = original_stack_tensor.unsqueeze(1)
    
    # Perform the interpolation
    resampled_stack_tensor = F.interpolate(original_stack_tensor, size=(new_height, new_width), mode='bilinear', align_corners=False)
    
    # Remove the channel dimension and move the tensor back to the CPU
    resampled_stack = resampled_stack_tensor.squeeze(1).cpu().numpy()

    return resampled_stack

# Usage of the PyTorch resample function
device = 'cuda'  # or 'cuda:0', 'cuda:1', etc., depending on the specific GPU device you want to use

yng_imgs_tr_array = resample_stack_pytorch(yng_imgs_tr_array, new_width, new_height, device)
yng_imgs_te_array = resample_stack_pytorch(yng_imgs_te_array, new_width, new_height, device)
old_imgs_tr_array = resample_stack_pytorch(old_imgs_tr_array, new_width, new_height, device)
old_imgs_te_array = resample_stack_pytorch(old_imgs_te_array, new_width, new_height, device)

# The rest of the code remains unchanged
print("Resampled young train image stack shape:", yng_imgs_tr_array.shape)
print("Resampled young test image stack shape:", yng_imgs_te_array.shape)
print("Resampled old train image stack shape:", old_imgs_tr_array.shape)
print("Resampled old test image stack shape:", old_imgs_te_array.shape)

In [ ]:
# Specify the file name
output_file = 'img_output.npz'

# Save the numpy arrays into one file
np.savez(output_file, yng_imgs_tr_array=yng_imgs_tr_array, yng_imgs_te_array=yng_imgs_te_array, old_imgs_tr_array=old_imgs_tr_array, old_imgs_te_array=old_imgs_te_array)

print("Numpy arrays saved to", output_file)

# Specify the output file names
ad_output_file = 'AD_data.npz'
age_output_file = 'age_data.npz'

# Save AD lists into a numpy compressed archive file
np.savez(ad_output_file, 
         yng_AD_tr=np.array(yng_AD_tr),
         yng_AD_te=np.array(yng_AD_te),
         old_AD_tr=np.array(old_AD_tr),
         old_AD_te=np.array(old_AD_te))

# Save age lists into a numpy compressed archive file
np.savez(age_output_file, 
         yng_age_tr=np.array(yng_age_tr),
         yng_age_te=np.array(yng_age_te),
         old_age_tr=np.array(old_age_tr),
         old_age_te=np.array(old_age_te))

print("AD data saved to", ad_output_file)
print("Age data saved to", age_output_file)

In [ ]:
# Specify the file name
output_file_100 = 'img_output_100.npz'

# Save the numpy arrays into one file with only 100 in the first dimension
np.savez(output_file_100, 
         yng_imgs_tr_array=yng_imgs_tr_array[:100,:,:],
         yng_imgs_te_array=yng_imgs_te_array[:100,:,:],
         old_imgs_tr_array=old_imgs_tr_array[:100,:,:],
         old_imgs_te_array=old_imgs_te_array[:100,:,:])

print("Numpy arrays with first dimension 100 saved to", output_file_100)

# Specify the output file names
ad_output_file_100 = 'AD_data_100.npz'
age_output_file_100 = 'age_data_100.npz'

# Save AD lists into a numpy compressed archive file with only 100 in the first dimension
np.savez(ad_output_file_100, 
         yng_AD_tr=np.array(yng_AD_tr[:100]),
         yng_AD_te=np.array(yng_AD_te[:100]),
         old_AD_tr=np.array(old_AD_tr[:100]),
         old_AD_te=np.array(old_AD_te[:100]))

# Save age lists into a numpy compressed archive file with only 100 in the first dimension
np.savez(age_output_file_100, 
         yng_age_tr=np.array(yng_age_tr[:100]),
         yng_age_te=np.array(yng_age_te[:100]),
         old_age_tr=np.array(old_age_tr[:100]),
         old_age_te=np.array(old_age_te[:100]))

print("AD data with first dimension 100 saved to", ad_output_file_100)
print("Age data with first dimension 100 saved to", age_output_file_100)